User.create!(email: 'antonio@lunchify.com', password: 'password', role: 'admin')
User.create!(email: 'employee@lunchify.com', password: 'password', role: 'employee')

Lunch.create!(name: 'Chicken and waffles')
Lunch.create!(name: 'Tacos')
Lunch.create!(name: 'Curry')
Lunch.create!(name: 'Pizza')
Lunch.create!(name: 'Sushi')
Lunch.create!(name: 'Breakfast')
Lunch.create!(name: 'Hamburgers')
Lunch.create!(name: 'Spaguetti')
Lunch.create!(name: 'Salmon')
Lunch.create!(name: 'Sandwiches')